/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import Mathlib.Logic.Function.DependsOn
public import Mathlib.Data.Set.Finite.Lattice
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real

/-!
# Interaction potentials

A potential is a family of real-valued functions indexed by finite subsets of the site set.
`Potential.IsPotential` is measurability of each term for `cylinderEvents` on its support.
`Potential.IsFiniteRange` is the locally finite case: only finitely many interacting supports
meet each site, so the Hamiltonian in a finite volume is a finite sum
(`interactingHamiltonian`).

`Potential.truncation` cuts a potential to the interactions contained in a finite volume.

Convergence of the Hamiltonian series in general is `Potential.IsSummable` in
`GibbsMeasure/Potential/Summable.lean`.
-/

@[expose] public section

open Set Finset MeasureTheory

variable {S E : Type*}

/-- A (multi-body) interaction potential: a family of real-valued functions indexed by finite
subsets of `S`. -/
abbrev Potential (S E : Type*) :=
  (Δ : Finset S) → (S → E) → ℝ

namespace Potential

variable {Φ : Potential S E}

/-- A family `Φ` is an interaction potential when each term `Φ Δ` is measurable with respect to
the σ-algebra generated by the coordinates in `Δ`. -/
class IsPotential [MeasurableSpace E] (Φ : Potential S E) : Prop where
  measurable (Δ : Finset S) :
    Measurable[cylinderEvents (X := fun _ : S ↦ E) (Δ : Set S)] (Φ Δ)

/-- `Φ` has finite range if each site belongs to only finitely many interacting supports. -/
class IsFiniteRange (Φ : Potential S E) : Prop where
  finite (i : S) : {A : Finset S | i ∈ A ∧ Φ A ≠ 0}.Finite

lemma IsFiniteRange.exists_finset (Φ : Potential S E) [IsFiniteRange Φ] (i : S) :
    ∃ Δ : Finset S, ∀ A : Finset S, i ∈ A → Φ A ≠ 0 → A ⊆ Δ := by
  classical
  refine ⟨(IsFiniteRange.finite (Φ := Φ) i).toFinset.sup id, fun A hi hΦ ↦ ?_⟩
  exact Finset.le_sup (f := id) (by simp [hi, hΦ])

/-- A finite range potential has, in each finite volume, only finitely many interacting terms. -/
lemma IsFiniteRange.finite_support (Φ : Potential S E) [IsFiniteRange Φ] (Λ : Finset S) :
    ({Δ : Finset S | ((Δ : Set S) ∩ (Λ : Set S)).Nonempty ∧ Φ Δ ≠ 0} : Set (Finset S)).Finite := by
  classical
  refine (Λ.finite_toSet.biUnion fun i _ ↦ IsFiniteRange.finite (Φ := Φ) i).subset ?_
  rintro A ⟨⟨x, hxA, hxΛ⟩, hΦ⟩
  exact Set.mem_biUnion (by simpa using hxΛ) ⟨by simpa using hxA, hΦ⟩

/-- The finite set of interaction supports that meet `Λ` and carry a nonzero interaction term. -/
noncomputable def interactingSupport [IsFiniteRange Φ] (Λ : Finset S) : Finset (Finset S) :=
  (IsFiniteRange.finite_support (Φ := Φ) Λ).toFinset

lemma mem_interactingSupport [IsFiniteRange Φ] {Λ Δ : Finset S} :
    Δ ∈ interactingSupport (Φ := Φ) Λ ↔
      ((Δ : Set S) ∩ (Λ : Set S)).Nonempty ∧ Φ Δ ≠ 0 := by
  simp [interactingSupport]

lemma interactingSupport_subset_of_subset [IsFiniteRange Φ] {Λ₁ Λ₂ : Finset S} (hΛ : Λ₁ ⊆ Λ₂) :
    interactingSupport (Φ := Φ) Λ₁ ⊆ interactingSupport (Φ := Φ) Λ₂ := by
  intro Δ hΔ
  rw [mem_interactingSupport] at hΔ ⊢
  exact ⟨hΔ.1.mono (inter_subset_inter_right _ (mod_cast hΛ)), hΔ.2⟩

/-- The interacting Hamiltonian in a volume `Λ`: the finite sum of all interaction terms whose
support meets `Λ`. -/
noncomputable def interactingHamiltonian [IsFiniteRange Φ] (Λ : Finset S) (η : S → E) : ℝ :=
  ∑ Δ ∈ interactingSupport (Φ := Φ) Λ, Φ Δ η

/-! ### Truncation to a finite volume -/

open Classical

/-- The truncation of `Φ` to interactions contained in `Δ`. -/
noncomputable def truncation (Φ : Potential S E) (Δ : Finset S) : Potential S E :=
  fun A η ↦ if A ⊆ Δ then Φ A η else 0

lemma truncation_of_subset {Δ B : Finset S} (h : B ⊆ Δ) : Φ.truncation Δ B = Φ B := by
  classical
  funext η; simp [truncation, h]

lemma truncation_of_not_subset {Δ B : Finset S} (h : ¬ B ⊆ Δ) : Φ.truncation Δ B = 0 := by
  classical
  funext η; simp [truncation, h]

instance (Δ : Finset S) : IsFiniteRange (Φ.truncation Δ) where
  finite i := by
    classical
    refine (Δ.powerset.finite_toSet).subset ?_
    intro A hA
    have : A ⊆ Δ := by
      by_contra h
      exact hA.2 (truncation_of_not_subset h)
    exact mem_powerset.2 this

section
variable [MeasurableSpace E]

/-- An interaction term depends only on the coordinates in its support. -/
lemma IsPotential.dependsOn [IsPotential Φ] (Δ : Finset S) :
    DependsOn (Φ Δ) (Δ : Set S) :=
  (IsPotential.measurable (Φ := Φ) Δ).dependsOn_of_cylinderEvents

lemma IsPotential.eq_of_eqOn [IsPotential Φ] {Δ : Finset S} {η ζ : S → E}
    (h : EqOn η ζ Δ) : Φ Δ η = Φ Δ ζ :=
  IsPotential.dependsOn (Φ := Φ) Δ fun x hx ↦ h (by exact_mod_cast hx)

@[fun_prop]
lemma measurable_interactingHamiltonian [IsFiniteRange Φ] [IsPotential Φ]
    (Λ : Finset S) : Measurable (interactingHamiltonian (Φ := Φ) Λ) := by
  classical
  refine Finset.measurable_sum _ fun A _ ↦
    (IsPotential.measurable (Φ := Φ) A).mono
      (cylinderEvents_le_pi (X := fun _ : S ↦ E) (Δ := (A : Set S))) le_rfl

instance (Δ : Finset S) [IsPotential Φ] : IsPotential (Φ.truncation Δ) where
  measurable B := by
    classical
    by_cases h : B ⊆ Δ
    · rw [truncation_of_subset h]
      exact IsPotential.measurable (Φ := Φ) B
    · rw [truncation_of_not_subset h]
      exact measurable_const

end

end Potential
