/-
Copyright (c) 2026 Matteo Cipollina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matteo Cipollina
-/
module

public import GibbsMeasure.Specification
public import Mathlib.Logic.Function.DependsOn
public import Mathlib.Analysis.SpecialFunctions.Exp
public import Mathlib.Algebra.BigOperators.Ring.Finset
public import Mathlib.Data.Set.Finite.Lattice
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic

/-!
# Interaction potentials

## Main definitions

* `Potential S E`: a family `Φ Δ : (S → E) → ℝ` indexed by the finite interaction supports.
* `Potential.IsPotential`: Georgii (2.2)(i), measurability of `Φ Δ` for `cylinderEvents Δ`.
* `Potential.IsFiniteRange`: Georgii (2.15).

Georgii (2.2)(ii), convergence of the Hamiltonian series, is `Potential.IsSummable` in
`GibbsMeasure/Potential/Summable.lean`.
-/

@[expose] public section

open scoped BigOperators

open ProbabilityTheory Set Finset MeasureTheory ENNReal

variable {S E : Type*} [MeasurableSpace E]

/-- A (multi-body) interaction potential: a family of real-valued functions indexed by finite
subsets of `S`. -/
def Potential (S E : Type*) [MeasurableSpace E] : Type _ :=
  (Δ : Finset S) → (S → E) → ℝ

namespace Potential

variable (Φ : Potential S E)

/-- **Georgii (2.2)(i).** A family `Φ` is an *interaction potential* when each interaction term
`Φ Δ` is measurable with respect to the σ-algebra generated by the coordinates in `Δ`.
(Georgii's *λ-admissibility* is the different condition (2.7), finiteness of the partition
function.) -/
class IsPotential (Φ : Potential S E) : Prop where
  measurable (Δ : Finset S) :
    Measurable[cylinderEvents (X := fun _ : S ↦ E) (Δ : Set S)] (Φ Δ)

/-- Georgii (2.15): `Φ` has *finite range* if for each site `i` there is a finite `Δ` containing
every interaction support that contains `i` and carries a nonzero term. -/
class IsFiniteRange (Φ : Potential S E) : Prop where
  exists_finset (i : S) : ∃ Δ : Finset S, ∀ A : Finset S, i ∈ A → Φ A ≠ 0 → A ⊆ Δ

/-- A finite range potential has, in each finite volume, only finitely many interacting terms. -/
lemma IsFiniteRange.finite_support (Φ : Potential S E) [IsFiniteRange Φ] (Λ : Finset S) :
    ({Δ : Finset S | ((Δ : Set S) ∩ (Λ : Set S)).Nonempty ∧ Φ Δ ≠ 0} : Set (Finset S)).Finite := by
  classical
  choose Δ hΔ using IsFiniteRange.exists_finset (Φ := Φ)
  refine Set.Finite.subset (Set.Finite.biUnion Λ.finite_toSet
    fun i _ ↦ (Δ i).powerset.finite_toSet) ?_
  rintro A ⟨⟨x, hxA, hxΛ⟩, hΦ⟩
  exact Set.mem_biUnion (by simpa using hxΛ)
    (by simpa using hΔ x A (by simpa using hxA) hΦ)

section Locality

variable {Φ}

/-- An interaction term depends only on the coordinates in its support. -/
lemma IsPotential.dependsOn [IsPotential Φ] (Δ : Finset S) :
    DependsOn (Φ Δ) (Δ : Set S) :=
  (IsPotential.measurable (Φ := Φ) Δ).dependsOn_of_cylinderEvents

lemma IsPotential.eq_of_eqOn [IsPotential Φ] {Δ : Finset S} {η ζ : S → E}
    (h : ∀ x ∈ Δ, η x = ζ x) : Φ Δ η = Φ Δ ζ :=
  IsPotential.dependsOn (Φ := Φ) Δ fun x hx ↦ h x (by exact_mod_cast hx)

end Locality

section InteractingHamiltonian

variable {Φ}

/-- The finite set of interaction supports that meet `Λ` and carry a nonzero interaction term. -/
noncomputable def interactingSupport [IsFiniteRange Φ] (Λ : Finset S) : Finset (Finset S) :=
  (IsFiniteRange.finite_support (Φ := Φ) Λ).toFinset

lemma mem_interactingSupport [IsFiniteRange Φ] {Λ Δ : Finset S} :
    Δ ∈ interactingSupport (Φ := Φ) Λ ↔
      ((Δ : Set S) ∩ (Λ : Set S)).Nonempty ∧ Φ Δ ≠ 0 := by
  simp [interactingSupport]

lemma interactingSupport_subset_of_subset [IsFiniteRange Φ] {Λ₁ Λ₂ : Finset S}
    (hΛ : Λ₁ ⊆ Λ₂) :
    interactingSupport (Φ := Φ) Λ₁ ⊆ interactingSupport (Φ := Φ) Λ₂ := by
  intro Δ hΔ
  rcases (mem_interactingSupport (Φ := Φ)).1 hΔ with ⟨⟨x, hxΔ, hxΛ₁⟩, hΦΔ⟩
  have hxΛ₂ : x ∈ (Λ₂ : Set S) := by
    have : x ∈ Λ₂ := hΛ (by simpa using hxΛ₁)
    simpa using this
  exact (mem_interactingSupport (Φ := Φ)).2 ⟨⟨x, hxΔ, hxΛ₂⟩, hΦΔ⟩

/-- The interacting Hamiltonian in a volume `Λ`: sum of all interaction terms whose support meets
`Λ`.

This is the standard finite-volume Hamiltonian \(H^{int}_Λ(η) = \sum_{Δ : Δ ∩ Λ ≠ ∅} Φ_Δ(η)\).
The local finiteness assumption ensures this is a finite sum. -/
noncomputable def interactingHamiltonian [IsFiniteRange Φ] (Λ : Finset S) (η : S → E) : ℝ :=
  Finset.sum (interactingSupport (Φ := Φ) Λ) (fun Δ => Φ Δ η)

lemma measurable_interactingHamiltonian [IsFiniteRange Φ] [IsPotential Φ] (Λ : Finset S) :
    Measurable (interactingHamiltonian (Φ := Φ) Λ) := by
  classical
  set t : Finset (Finset S) := interactingSupport (Φ := Φ) Λ with ht
  change Measurable (fun η : S → E => Finset.sum t (fun Δ => Φ Δ η))
  refine Finset.induction_on t ?_ ?_
  · simp
  · intro a s ha hs_meas
    have ha_meas : Measurable (fun η : S → E => Φ a η) :=
      (IsPotential.measurable (Φ := Φ) a).mono
        (cylinderEvents_le_pi (X := fun _ : S ↦ E) (Δ := (a : Set S))) le_rfl
    simpa [Finset.sum_insert ha, Pi.add_def] using ha_meas.add hs_meas

/-! ### Boltzmann weights and the cocycle identity -/

/-- Unnormalized Boltzmann weight `exp (-β H^{int}_Λ(η))` — Georgii's Boltzmann factor `h_Λ`,
eq. (2.4) — valued in `ℝ≥0∞`. -/
noncomputable def boltzmannWeight [IsFiniteRange Φ] (β : ℝ) (Λ : Finset S) (η : S → E) : ℝ≥0∞ :=
  ENNReal.ofReal (Real.exp (-β * interactingHamiltonian (Φ := Φ) Λ η))

lemma measurable_boltzmannWeight [IsFiniteRange Φ] [IsPotential Φ] (β : ℝ) (Λ : Finset S) :
    Measurable (boltzmannWeight (Φ := Φ) β Λ) := by
  have hH : Measurable fun η : S → E => interactingHamiltonian (Φ := Φ) Λ η :=
    measurable_interactingHamiltonian (Φ := Φ) Λ
  have h :
      boltzmannWeight (Φ := Φ) β Λ =
        fun x ↦ ENNReal.ofReal (Real.exp (-β * interactingHamiltonian (Φ := Φ) Λ x)) := by
    funext x
    rfl
  rw [h]
  exact ((measurable_const.mul hH).exp).ennreal_ofReal

lemma interactingHamiltonian_sub_eq_sum_sub [IsFiniteRange Φ]
    (Λ : Finset S) (η ζ : S → E) :
    interactingHamiltonian (Φ := Φ) Λ η - interactingHamiltonian (Φ := Φ) Λ ζ =
      Finset.sum (interactingSupport (Φ := Φ) Λ) (fun Δ => Φ Δ η - Φ Δ ζ) := by
  simp [interactingHamiltonian, Finset.sum_sub_distrib]

lemma interactingHamiltonian_sub_eq_of_subset_eqOn_compl
    [IsFiniteRange Φ] [IsPotential Φ] {Λ₁ Λ₂ : Finset S}
    (hΛ : Λ₁ ⊆ Λ₂) {η ζ : S → E} (hrestrict : ∀ s ∉ Λ₁, ζ s = η s) :
    interactingHamiltonian (Φ := Φ) Λ₁ η - interactingHamiltonian (Φ := Φ) Λ₁ ζ =
      interactingHamiltonian (Φ := Φ) Λ₂ η - interactingHamiltonian (Φ := Φ) Λ₂ ζ := by
  have hsubset := interactingSupport_subset_of_subset (Φ := Φ) hΛ
  rw [interactingHamiltonian_sub_eq_sum_sub, interactingHamiltonian_sub_eq_sum_sub]
  refine Finset.sum_subset hsubset ?_
  intro Δ hΔ₂ hΔ₁
  have hΔ₂' := (mem_interactingSupport (Φ := Φ)).1 hΔ₂
  have hΔ₁' :
      ¬ (((Δ : Set S) ∩ (Λ₁ : Set S)).Nonempty ∧ Φ Δ ≠ 0) := by
    intro h
    exact hΔ₁ ((mem_interactingSupport (Φ := Φ)).2 h)
  have hΔ_out : ∀ x ∈ Δ, x ∉ Λ₁ := by
    intro x hxΔ hxΛ₁
    exact hΔ₁' ⟨⟨x, by simpa using hxΔ, by simpa using hxΛ₁⟩, hΔ₂'.2⟩
  have hΦΔ : Φ Δ η = Φ Δ ζ := by
    apply IsPotential.eq_of_eqOn (Φ := Φ) (Δ := Δ) (η := η) (ζ := ζ)
    intro x hxΔ
    exact (hrestrict x (hΔ_out x hxΔ)).symm
  simp [hΦΔ]

lemma boltzmannWeight_mul_comm_of_hamiltonian_sum_eq [IsFiniteRange Φ]
    (β : ℝ) {Λ₁ Λ₂ : Finset S} {η ζ : S → E}
    (hsum :
      interactingHamiltonian (Φ := Φ) Λ₂ ζ + interactingHamiltonian (Φ := Φ) Λ₁ η =
        interactingHamiltonian (Φ := Φ) Λ₁ ζ + interactingHamiltonian (Φ := Φ) Λ₂ η) :
    boltzmannWeight (Φ := Φ) β Λ₂ ζ * boltzmannWeight (Φ := Φ) β Λ₁ η =
      boltzmannWeight (Φ := Φ) β Λ₁ ζ * boltzmannWeight (Φ := Φ) β Λ₂ η := by
  let H (Λ : Finset S) (σ : S → E) : ℝ := interactingHamiltonian (Φ := Φ) Λ σ
  have hargs :
      (-β * H Λ₂ ζ) + (-β * H Λ₁ η) = (-β * H Λ₁ ζ) + (-β * H Λ₂ η) := by
    simpa [H, mul_add, add_comm, add_left_comm, add_assoc, mul_assoc] using
      congrArg (fun x => (-β) * x) hsum
  have h_exp :
      Real.exp (-β * H Λ₂ ζ) * Real.exp (-β * H Λ₁ η) =
        Real.exp (-β * H Λ₁ ζ) * Real.exp (-β * H Λ₂ η) := by
    calc
      Real.exp (-β * H Λ₂ ζ) * Real.exp (-β * H Λ₁ η)
          = Real.exp ((-β * H Λ₂ ζ) + (-β * H Λ₁ η)) := by
              simpa using (Real.exp_add (-β * H Λ₂ ζ) (-β * H Λ₁ η)).symm
      _ = Real.exp ((-β * H Λ₁ ζ) + (-β * H Λ₂ η)) := congrArg Real.exp hargs
      _ = Real.exp (-β * H Λ₁ ζ) * Real.exp (-β * H Λ₂ η) := by
            simpa using (Real.exp_add (-β * H Λ₁ ζ) (-β * H Λ₂ η))
  dsimp [boltzmannWeight, H]
  calc
    ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₂ ζ)) *
        ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₁ η))
        = ENNReal.ofReal
            (Real.exp (-β * interactingHamiltonian Λ₂ ζ) *
              Real.exp (-β * interactingHamiltonian Λ₁ η)) := by
            exact (ENNReal.ofReal_mul (Real.exp_pos _).le).symm
    _ = ENNReal.ofReal
          (Real.exp (-β * interactingHamiltonian Λ₁ ζ) *
            Real.exp (-β * interactingHamiltonian Λ₂ η)) := by
          simpa [H] using congrArg ENNReal.ofReal h_exp
    _ = ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₁ ζ)) *
        ENNReal.ofReal (Real.exp (-β * interactingHamiltonian Λ₂ η)) := by
          exact ENNReal.ofReal_mul (Real.exp_pos _).le

lemma boltzmannWeight_mul_comm_of_hamiltonian_sub_eq [IsFiniteRange Φ]
    (β : ℝ) {Λ₁ Λ₂ : Finset S} {η ζ : S → E}
    (hH :
      interactingHamiltonian (Φ := Φ) Λ₁ η - interactingHamiltonian (Φ := Φ) Λ₁ ζ =
        interactingHamiltonian (Φ := Φ) Λ₂ η - interactingHamiltonian (Φ := Φ) Λ₂ ζ) :
    boltzmannWeight (Φ := Φ) β Λ₂ ζ * boltzmannWeight (Φ := Φ) β Λ₁ η =
      boltzmannWeight (Φ := Φ) β Λ₁ ζ * boltzmannWeight (Φ := Φ) β Λ₂ η := by
  let H (Λ : Finset S) (σ : S → E) : ℝ := interactingHamiltonian (Φ := Φ) Λ σ
  have hsum : H Λ₂ ζ + H Λ₁ η = H Λ₁ ζ + H Λ₂ η := by
    have : H Λ₁ η + H Λ₂ ζ = H Λ₂ η + H Λ₁ ζ :=
      (sub_eq_sub_iff_add_eq_add).1 hH
    calc
      H Λ₂ ζ + H Λ₁ η = H Λ₁ η + H Λ₂ ζ := by simp [add_comm]
      _ = H Λ₂ η + H Λ₁ ζ := this
      _ = H Λ₁ ζ + H Λ₂ η := by simp [add_comm]
  exact boltzmannWeight_mul_comm_of_hamiltonian_sum_eq (Φ := Φ) β hsum

/-- The cocycle identity for interacting Boltzmann weights (the pre-modification identity of
Georgii's Definition (1.31); cf. Proposition (2.5)), expressed as
`Specification.IsPremodifier`. -/
lemma isPremodifier_boltzmannWeight (β : ℝ) [IsFiniteRange Φ] [IsPotential Φ] :
    Specification.IsPremodifier (S := S) (E := E) (boltzmannWeight (Φ := Φ) β) := by
  refine ⟨?_, ?_⟩
  · intro Λ
    exact measurable_boltzmannWeight (Φ := Φ) β Λ
  · intro Λ₁ Λ₂ ζ η hΛ hrestrict
    exact boltzmannWeight_mul_comm_of_hamiltonian_sub_eq (Φ := Φ) β
      (interactingHamiltonian_sub_eq_of_subset_eqOn_compl (Φ := Φ) hΛ hrestrict)

end InteractingHamiltonian
end Potential
